[FIX] status should work

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -92,7 +92,7 @@ runs:
         [ -d "./.github/build" ] && echo echo "::set-output name=exists::1" || echo "::set-output name=exists::0"
 
     - name: Run Build Script
-      if: steps.build-script.outputs.exists == '1' && steps.check.outputs.skip == 'false'
+      if: steps.build-script.outputs.exists == '0' && steps.check.outputs.skip == 'false'
       uses: ./.github/build
       with:
         env: ${{ inputs.env }}
@@ -124,6 +124,7 @@ runs:
 
     - name: Deploy Chart
       if: steps.check.outputs.skip == 'false'
+      id: deployment
       env:
         SERVICE_NAME: ${{ inputs.service-name }}
         HELM_CHART: ${{ inputs.helm-chart }}
@@ -133,11 +134,20 @@ runs:
       run: |
         sed -i "s/^appVersion:.*$/appVersion: \"$VERSION\"/" $HELM_CHART/Chart.yaml
         helm upgrade $SERVICE_NAME $HELM_CHART --install --atomic --create-namespace -f ./deployment/values/${{ inputs.env }}.yml --set image=$SHA_IMAGE --set version=$VERSION
+        echo "::set-output name=success::1"
 
-    - uses: ravsamhq/notify-slack-action@v1
-      if: ${{ always() && steps.check.outputs.skip == 'false' }}
+    - name: Determine Deployment Status
+      if: always()
+      id: status
+      shell: bash
+      run: |
+        [ ${{ steps.deployment.outputs.success == '1' $}} ] && echo echo "::set-output name=value::success" || echo "::set-output name=value::failure"
+
+    - name: Notify of Deployment
+      uses: ravsamhq/notify-slack-action@v1
+      if: always() && steps.check.outputs.skip == 'false'
       with:
-        status: ${{ job.status }}
+        status: ${{ steps.status.outputs.value }}
         notification_title: '<${{ github.server_url }}/InvictusApps/${{ inputs.service-name }}|${{ inputs.service-name }}> {status_message} deployment to *${{ inputs.cluster-name }}*'
         message_format: '{emoji} *${{ steps.current-ref.outputs.message }}*'
         footer: '<${{ github.server_url }}/InvictusApps/${{ inputs.service-name }}/commit/${{ steps.current-ref.outputs.head }}|View Head Commit>  | <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View {workflow} Run>'
